query FamilyGetDeathAnniversaries(
  $name: String
  $page: Int
  $orderBy: [OrderBy!]
  $status: EDeathAnniversaryStatus
  $take: Int
  $tombAddress: String
  $requesterName: String
  $deathAnniversaryTypes: [EDeathAnniversaryType!]
) {
  familyGetDeathAnniversaries(
    name: $name
    page: $page
    orderBy: $orderBy
    status: $status
    requesterName: $requesterName
    take: $take
    tombAddress: $tombAddress
    deathAnniversaryTypes: $deathAnniversaryTypes
  ) {
    timestamp
    statusCode
    errorMessage
    errorCode
    data {
      totalPages
      totalItems
      take
      page
      data {
        id
        desiredStartTime
        desiredEndTime
        actualStartTime
        actualEndTime
        enableUpdate
        finishedImage
        isLiveStream
        linkLiveStream
        readyImage
        rejectReason
        status
        note
        deathAnniversaryType
        creatorId
        deathAnniversaryOfferings {
          id
          offeringId
          offering {
            id
            name
            image
          }
        }
        deceased {
          id
          userDetail {
            id
            avatar
            name
          }
          tombAddress
          rejectReason
        }
        user {
          id
          email
          userDetail {
            id
            avatar
            name
            phone
          }
        }
      }
    }
  }
}
