mutation templeUpdateDeathAnniversary(
  $templeUpdateDeathAnniversaryInput: TempleUpdateDeathAnniversaryInput!
) {
  templeUpdateDeathAnniversary(
    templeUpdateDeathAnniversaryInput: $templeUpdateDeathAnniversaryInput
  ) {
    errorCode
  }
}


