mutation RemoveFamilyMember($removeFamilyMemberInput: RemoveFamilyMemberInput!) {
  removeFamilyMember(removeFamilyMemberInput: $removeFamilyMemberInput) {
    timestamp
    statusCode
    errorMessage
    errorCode
  }
}
