query getListDeceased($familyId: Int!) {
  getListDeceased(familyId: $familyId) {
    timestamp
    statusCode
    errorMessage
    errorCode
    data {
      data {
        description
        creatorId
        dateOfDeath
        familyId
        id
        templeId
        userDetail {
          address
          avatar
          birthday
          citizenNumber
          gender
          name
        }
        images {
          id
          image
        }
      }
    }
  }
}
