mutation eventParticipantCheckIn($eventParticipantCheckInInput: VEventParticipantCheckInInput!) {
  eventParticipantCheckIn(eventParticipantCheckInInput: $eventParticipantCheckInInput) {
    timestamp
    statusCode
    errorMessage
    errorCode
  }
}
