query GetEvents($page: Int, $take: Int, $templeId: Int) {
  getEvents(page: $page, take: $take, templeId: $templeId) {
    data {
      totalItems
      take
      page
      totalPages
      data {
        id
        name
        avatar
        startDateBooking
        startDateEvent
        endDateEvent
        endDateBooking
        maxParticipant
        address
      }
    }
  }
}

