query GetEventById($id: Int!) {
  getEventById(id: $id) {
    timestamp
    statusCode
    errorMessage
    errorCode
    data {
      id
      name
      address
      avatar
      createdAt
      creatorId
      description
      email
      endDateBooking
      endDateEvent
      maxParticipant
      phone
      priority
      priorityExpired
      startDateBooking
      startDateEvent
      currentParticipant
      isBooked
      images {
        id
        image
      }
      eventParticipantTypes {
        role
      }
    }
  }
}
