mutation familyUpdateDeathAnniversary(
  $updateDeathAnniversaryInput: UpdateDeathAnniversaryInput!
) {
  familyUpdateDeathAnniversary(
    updateDeathAnniversaryInput: $updateDeathAnniversaryInput
  ) {
    errorCode
  }
}

mutation cancelDeathAnniversary(
  $cancelDeathAnniversaryInput: CancelDeathAnniversaryInput!
) {
  cancelDeathAnniversary(cancelDeathAnniversaryInput: $cancelDeathAnniversaryInput) {
    errorCode
  }
}