mutation createDeathAnniversary(
  $createDeathAnniversaryInput: CreateDeathAnniversaryInput!
) {
  createDeathAnniversary(
    createDeathAnniversaryInput: $createDeathAnniversaryInput
  ) {
    errorCode
  }
}
