mutation createDeathAnniversary(
  $createDeathAnniversaryInput: CreateDeathAnniversaryInput!
) {
  createDeathAnniversary(
    createDeathAnniversaryInput: $createDeathAnniversaryInput
  ) {
    errorCode
  }
}

mutation deleteDeceased($id: Int!) {
  deleteDeceased(id: $id) {
    errorCode
  }
}
