query getDeceased($id: Int!) {
  getDeceased(id: $id) {
    data {
      images {
        id
        image
      }
      dateOfDeath
      description
      createdAt
      userDetail {
        avatar
        birthday
        citizenNumber
        address
        name
        gender
      }
    }
  }
}
