query GetUser {
  getUser {
    data {
      createdAt
      email
      familyId
      templeId
      id
      role
      userDetail {
        id
        avatar
        name
        gender
        birthday
        phone
        address
      }
      followerTemples {
        id
        templeId
      }
    }
    timestamp
    statusCode
    errorMessage
    errorCode
  }
}
