query FamilyGetListDeceased($page: Int, $take: Int, $keyword: String) {
  familyGetListDeceased(page: $page, take: $take, keyword: $keyword) {
    timestamp
    statusCode
    errorMessage
    errorCode
    data {
      totalItems
      data {
        description
        creatorId
        dateOfDeath
        familyId
        id
        templeId
        userDetail {
          address
          avatar
          birthday
          citizenNumber
          gender
          name
        }
        images {
          id
          image
        }
      }
    }
  }
}
