mutation UserLogin($input: UserLoginInput!) {
  userLogin(input: $input) {
    data {
      accessToken
      refreshToken
      user {
        role
        name
        id
        email
        avatar
      }
    }
    errorCode
    errorMessage
    statusCode
    timestamp
  }
}
