mutation RemoveTempleMember($removeTempleMemberInput: VRemoveTempleMemberInput! ) {
  removeTempleMember(removeTempleMemberInput: $removeTempleMemberInput) {
    timestamp
    statusCode
    errorMessage
    errorCode
  }
}
