mutation updateEventParticipant($bookingEventInput: UpdateEventParticipantInput!) {
  updateEventParticipant(bookingEventInput: $bookingEventInput) {
    timestamp
    statusCode
    errorMessage
    errorCode
  }
}
