mutation AddDeceasedImage($addDeceasedImageInput: VAddDeceasedImageInput!) {
  addDeceasedImage(addDeceasedImageInput: $addDeceasedImageInput) {
    timestamp
    statusCode
    errorMessage
    errorCode
  }
}
