query getDeceased($id: Int!) {
  getDeceased(id: $id) {
    data {
      images {
        id
        image
      }
      dateOfDeath
      description
      createdAt
      updatedAt
      templeId
      modifier {
        id
        userDetail {
          id
          name
        }
      }
      userDetail {
        id
        avatar
        birthday
        citizenNumber
        address
        name
        gender
      }
      deathAnniversaries {
        id
      }
    }
  }
}
