export enum ERole {
  SYSTEM = "SYSTEM",
  FAMILY_ADMIN = "FAMILY_ADMIN",
  FAMILY_MEMBER = "FAMILY_MEMBER",
  TEMPLE_ADMIN = "TEMPLE_ADMIN",
  PUBLIC_USER = "PUBLIC_USER",
}

export enum EGender {
  MALE = 0,
  FEMALE = 1,
  OTHER = 2,
}
