mutation ResponseFamilyInvitation($responseInviteFamilyInput: ResponseInviteFamilyInput!) {
  responseFamilyInvitation(
    responseInviteFamilyInput: $responseInviteFamilyInput
  ) {
    timestamp
    statusCode
    errorMessage
    errorCode
  }
}

mutation UpdateNotification($updateNotificationInput: UpdateNotificationInput!) {
  updateNotification(updateNotificationInput: $updateNotificationInput) {
    timestamp
    statusCode
    errorMessage
    errorCode
  }
}

