mutation ResponseFamilyInvitation($responseInviteFamilyInput: ResponseInviteFamilyInput!) {
  responseFamilyInvitation(
    responseInviteFamilyInput: $responseInviteFamilyInput
  ) {
    timestamp
    statusCode
    errorMessage
    errorCode
  }
}
