query templeGetEvents($upcoming: Boolean , $onGoing: Boolean,$ended: Boolean, $isFreeOpen: Boolean, $page: Int, $skip: Int, $take: Int, $name: String, $orderBy: [OrderBy!]) {
  templeGetEvents(upcoming: $upcoming,onGoing: $onGoing,ended: $ended, isFreeOpen: $isFreeOpen, page: $page, skip: $skip, take: $take, name: $name, orderBy: $orderBy) {
    data {
      totalItems
      take
      page
      totalPages
      data {
        id
        name
        avatar
        startDateBooking
        startDateEvent
        endDateEvent
        endDateBooking
        maxParticipant
        isFreeOpen
        address
        currentParticipant
        bookingParticipant
        checkInParticipant
        createdAt
        eventParticipantTypes {
          role
        }
      }
    }
  }
}
