mutation UpdateStatusTemple($updateStatusTempleInput: VUpdateStatusTempleInput!) {
  updateStatusTemple(updateStatusTempleInput: $updateStatusTempleInput) {
    timestamp
    statusCode
    errorMessage
    errorCode
  }
}
