mutation AddTempleMember($addTempleMemberInput: VAddTempleMemberInput!) {
  addTempleMember(addTempleMemberInput: $addTempleMemberInput) {
    timestamp
    statusCode
    errorMessage
    errorCode
  }
}
