mutation UpdateUser($updateUserDetailInput: VUpdateUserDetailInput = {}) {
  updateUser(updateUserDetailInput: $updateUserDetailInput) {
    timestamp
    statusCode
    errorMessage
    errorCode
  }
}
