query getTemples($keyword: String, $page: Int, $take: Int) {
  getTemples(query: { keyword: $keyword, page: $page, take: $take}) {
    errorCode
    errorMessage
    statusCode
    timestamp
    data {
      totalPages
      totalItems
      take
      page
      data {
        address
        adminId
        avatar
        createdAt
        description
        email
        id
        name
        phone
        # plan
        # planExpired
        # priority
        # priorityExpired
        status
        updatedAt
        website
      }
    }
  }
}
