mutation updateStatusDeathAnniversary(
  $updateStatusDeathAnniversaryInput: UpdateStatusDeathAnniversaryInput!
) {
  updateStatusDeathAnniversary(
    updateStatusDeathAnniversaryInput: $updateStatusDeathAnniversaryInput
  ) {
    errorCode
  }
}
