query getEventParticipants(
  $eventId: Int!
  $bookingStatus: EBookingStatus!
  $page: Int
  $take: Int
  $name: String
  $email: String
  $address: String
  $familyKeyword: String
  $isFollowing: Boolean
  $orderBy: [OrderBy!]
) {
  getEventParticipants(
    eventId: $eventId
    bookingStatus: $bookingStatus
    page: $page
    take: $take
    name: $name
    email: $email
    address: $address
    familyKeyword: $familyKeyword
    isFollowing: $isFollowing
    orderBy: $orderBy
  ) {
    statusCode
    errorMessage
    errorCode
    data {
      totalPages
      totalItems
      take
      page
      data {
        id
        rejectReason
        checkInAt
        familyName
        familyCode
        isFollowing
        user {
          id
          email
          userDetail {
            avatar
            address
            name
          }
        }
        approver {
          id
          userDetail {
            name
          }
        }
        event{
          endDateBooking
        }
        createdAt
        updatedAt
      }
    }
  }
}
